Taarafo.Portal.Web/Brokers/Loggings/LoggingBroker.cs
Taarafo.Portal.Web/Taarafo.Portal.Web.csproj
Taarafo.Portal.Web/Views/Bases/ButtonBase.razor
Taarafo.Portal.Web/Views/Bases/ButtonBase.razor.cs

Similar to Brokers, Bases do not require testing as this will be taken care of in Components.
I include a screen to see all properties working
#15  Ref to issue

BASE: Button Base

---

README.md

DOCUMENTATION: Update The Readme of The Project

---

Taarafo.Portal.Web/Brokers/Loggings/LoggingBroker.cs

Fix issue #23 that you also encountered in the video https://www.youtube.com/watch?v=yF-_HGC7_XM at minute 33

MAJOR FIX: Unable to resolve dependencies in application

---

.editorconfig

CONFIG: Addition of solution level .editorconfig

---

Taarafo.Portal.Web/Taarafo.Portal.Web.csproj
Taarafo.Portal.Web/Views/Bases/DialogBase.razor
Taarafo.Portal.Web/Views/Bases/DialogBase.razor.cs
Taarafo.Portal.Web/Views/Pages/Index.razor
Taarafo.Portal.Web/Views/Pages/Index.razor.cs
Taarafo.Portal.sln

BASE: Dialog Base

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs
Taarafo.Portal.Web/Brokers/API/ApiBroker.Posts.cs
Taarafo.Portal.Web/Brokers/API/IApiBroker.Posts.cs
Taarafo.Portal.Web/Services/Foundations/Posts/IPostService.cs
Taarafo.Portal.Web/Services/Foundations/Posts/PostService.Expections.cs
Taarafo.Portal.Web/Services/Foundations/Posts/PostService.cs

FOUNDATIONS: Retrieve All Posts

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Logic.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs
Taarafo.Portal.Web.Tests.Unit/Services/PostViews/PostViewServiceTests.Exceptions.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/PostViews/PostViewServiceTests.Logic.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/PostViews/PostViewServiceTests.cs
Taarafo.Portal.Web/Brokers/API/ApiBroker.Posts.cs
Taarafo.Portal.Web/Brokers/API/IApiBroker.Posts.cs
Taarafo.Portal.Web/Models/PostViews/Exceptions/FailedPostViewServiceException.cs
Taarafo.Portal.Web/Models/PostViews/Exceptions/PostViewDependencyException.cs
Taarafo.Portal.Web/Models/PostViews/Exceptions/PostViewServiceException.cs
Taarafo.Portal.Web/Models/PostViews/PostView.cs
Taarafo.Portal.Web/Models/Posts/Exceptions/PostDependencyException.cs
Taarafo.Portal.Web/Models/Posts/Exceptions/PostServiceException.cs
Taarafo.Portal.Web/Services/Foundations/Posts/IPostService.cs
Taarafo.Portal.Web/Services/Foundations/Posts/PostService.Expections.cs
Taarafo.Portal.Web/Services/Foundations/Posts/PostService.cs
Taarafo.Portal.Web/Services/PostViews/IPostViewService.cs
Taarafo.Portal.Web/Services/PostViews/PostViewService.Exceptions.cs
Taarafo.Portal.Web/Services/PostViews/PostViewService.cs
Taarafo.Portal.Web/Startup.cs

VIEWS: Retrieve All Post Views

---

Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Plans.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/CloudBroker.ResourceGroups.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Storages.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/CloudBroker.WebApps.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Plans.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.ResourceGroup.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Storages.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.WebApps.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Configurations/ConfigurationBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Configurations/IConfigurationBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Loggings/ILoggingBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Brokers/Loggings/LoggingBroker.cs
Taarafo.Portal.Web.Infrastructure.Provision/Models/Configurations/CloudAction.cs
Taarafo.Portal.Web.Infrastructure.Provision/Models/Configurations/CloudManagementConfiguration.cs
Taarafo.Portal.Web.Infrastructure.Provision/Models/Storages/SqlDatabase.cs
Taarafo.Portal.Web.Infrastructure.Provision/Models/Storages/SqlDatabaseAccess.cs
Taarafo.Portal.Web.Infrastructure.Provision/Program.cs
Taarafo.Portal.Web.Infrastructure.Provision/Services/Foundations/CloudManagements/CloudManagementService.cs
Taarafo.Portal.Web.Infrastructure.Provision/Services/Foundations/CloudManagements/ICloudManagementService.cs
Taarafo.Portal.Web.Infrastructure.Provision/Services/Processings/CloudManagementProcessingService.cs
Taarafo.Portal.Web.Infrastructure.Provision/Services/Processings/ICloudManagementProcessingService.cs
Taarafo.Portal.Web.Infrastructure.Provision/Taarafo.Portal.Web.Infrastructure.Provision.csproj
Taarafo.Portal.Web.Infrastructure.Provision/appSetttings.json
Taarafo.Portal.sln

PROVISION: Blazor Project

---

Taarafo.Portal.Web/Views/Bases/CardBase.razor
Taarafo.Portal.Web/Views/Bases/CardBase.razor.cs
Taarafo.Portal.Web/Views/Pages/Index.razor
Taarafo.Portal.Web/Views/Pages/Index.razor.cs

BASE: Creating Base Card

---

Taarafo.Portal.Web.Tests.Unit/Services/PostViews/PostViewServiceTests.cs
Taarafo.Portal.Web/Models/PostViews/PostView.cs
Taarafo.Portal.Web/Models/Posts/Post.cs

CODE RUB: Post and PostView Author property to string

---

Taarafo.Portal.Web/Views/Bases/SpinnerBase.razor
Taarafo.Portal.Web/Views/Bases/SpinnerBase.razor.cs
Taarafo.Portal.Web/Views/Pages/Index.razor
Taarafo.Portal.Web/Views/Pages/Index.razor.cs

I want to resolve #66 
Example:

BASE: Spinner

---

Taarafo.Portal.Web/Brokers/API/ApiBroker.Comments.cs
Taarafo.Portal.Web/Brokers/API/IApiBroker.Comments.cs
Taarafo.Portal.Web/Models/Comments/Comment.cs

BROKERS: Post Comment

---

Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Exceptions.Add.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Exceptions.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Exceptions.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Logic.Add.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Logic.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Logic.RetrieveAll.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Validations.Add.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.Validations.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Views/PostViews/PostViewServiceTests.cs
Taarafo.Portal.Web.Tests.Unit/Taarafo.Portal.Web.Tests.Unit.csproj
Taarafo.Portal.Web/Models/PostViews/Exceptions/NullPostViewException.cs
Taarafo.Portal.Web/Services/Foundations/Authors/AuthorService.cs
Taarafo.Portal.Web/Services/Foundations/Authors/IAuthorService.cs
Taarafo.Portal.Web/Services/Views/PostViews/IPostViewService.cs
Taarafo.Portal.Web/Services/Views/PostViews/PostViewService.Exceptions.cs
Taarafo.Portal.Web/Services/Views/PostViews/PostViewService.Validations.cs
Taarafo.Portal.Web/Services/Views/PostViews/PostViewService.cs
Taarafo.Portal.Web/Startup.cs

VIEWS: Post Add

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Add.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.Add.cs.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.Add.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/CommentDependencyException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/CommentDependencyValidationException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/CommentServiceException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/CommentValidationException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/FailedCommentDependencyException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/FailedCommentServiceException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/InvalidCommentException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/LockedCommentException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/NotFoundCommentException.cs
Taarafo.Portal.Web/Models/Comments/Exceptions/NullCommentException.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.Expections.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.Validations.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.cs
Taarafo.Portal.Web/Services/Foundations/Comments/ICommentService.cs
Taarafo.Portal.Web/Startup.cs

FOUNDATIONS: Add Comment

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs
Taarafo.Portal.Web/Brokers/Apis/ApiBroker.Comments.cs
Taarafo.Portal.Web/Brokers/Apis/ApiBroker.Posts.cs
Taarafo.Portal.Web/Brokers/Apis/ApiBroker.cs
Taarafo.Portal.Web/Brokers/Apis/IApiBroker.Comments.cs
Taarafo.Portal.Web/Brokers/Apis/IApiBroker.Posts.cs
Taarafo.Portal.Web/Brokers/Apis/IApiBroker.cs
Taarafo.Portal.Web/Services/Foundations/Posts/PostService.cs
Taarafo.Portal.Web/Startup.cs

CODE RUB: Rename Brokers/API to Brokers/Apis

---

Taarafo.Portal.Web/Program.cs
Taarafo.Portal.Web/Startup.cs
Taarafo.Portal.Web/Taarafo.Portal.Web.csproj
Taarafo.Portal.Web/appsettings.Development.json

CONFIG:  Addition of user-secrets for obtaining the Syncfusion License

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RetrieveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.RetrieveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RetrieveById.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.Validations.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.cs
Taarafo.Portal.Web/Services/Foundations/Comments/ICommentService.cs

FOUNDATIONS: Retrieve Comment By Id

---

Taarafo.Portal.Web.Infrastructure.Build/Program.cs

MAJORFIX: Fix Target Branch in Build

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Modify.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.Modify.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.Modify.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.Validations.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.cs
Taarafo.Portal.Web/Services/Foundations/Comments/ICommentService.cs

FOUNDATIONS: Modify Comment

---

Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.RemoveById.cs
Taarafo.Portal.Web.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RemoveById.cs
Taarafo.Portal.Web/Services/Foundations/Comments/CommentService.cs
Taarafo.Portal.Web/Services/Foundations/Comments/ICommentService.cs

FOUNDATIONS: Remove Comments By Id

---

.github/workflows/dotnet.yml
Taarafo.Portal.Web.Infrastructure.Build/Program.cs

CONFIG: Update .NET Version to 6.0.101

---

README.md

@hassanhabib Please review and merge.

DOCUMENTATIONS: Readme Badge Versioning
